[tox]
env_list = lint, typecheck, test
#toxworkdir = {env:HOME}/.tox/eink-dashboard

[testenv]
base_python = python3

[testenv:lint]
skip_install = true
deps = ruff>=0.11
commands =
    ruff check .
    ruff format --check .

[testenv:typecheck]
skip_install = true
deps =
    Pillow>=12.0
    aiohttp>=3.0
    ty
commands =
    ty check

[testenv:test]
skip_install = true
deps =
    Pillow>=12.0
    aiohttp>=3.0
    pytest>=8.0
    pytest-asyncio>=1.0
commands =
    pytest {posargs}
